version: '3.8'
services:
  db:
    image: postgres:11-alpine
    container_name: gamil_db
    restart: unless-stopped
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    container_name: gamil_app
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    container_name: gamil_nginx
    restart: unless-stopped
    image: "nginx:latest"
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - app
 