# Generated by Django 3.2.6 on 2022-02-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArteryEmbolizationModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_points",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("3", "3 месяца"),
                            ("6", "6 месяцев"),
                            ("12", "12 месяцев"),
                            ("24", "24 месяца"),
                            ("36", "36 месяцев"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Контрольные точки динамического наблюдения пациенток после проведенной ЭМА",
                    ),
                ),
                (
                    "performance_criteria",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Критерии эффективности",
                    ),
                ),
                (
                    "menstrual_function",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Менструальная функция",
                    ),
                ),
                (
                    "menarche",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("24-38/3-8", "24-38/3-8"),
                            ("24-38/>8", "24-38/>8"),
                            ("23 и </3-8", "23 и </3-8"),
                            ("23 и </>8", "23 и </>8"),
                            ("другое", "другое"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Цикличность менструальных выделений",
                    ),
                ),
                (
                    "periods_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Обильные", "Обильные"),
                            ("нормальные", "нормальные"),
                            ("судные", "судные"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "complaints_1",
                    models.BooleanField(
                        verbose_name="боль в пояснице, боли внизу живота, снижающие качество жизни"
                    ),
                ),
                (
                    "complaints_2",
                    models.BooleanField(
                        verbose_name="симптомы сдавления смежных органов (прямая кишка, мочевой пузырь, мочеточники)"
                    ),
                ),
                (
                    "complaints_3",
                    models.BooleanField(verbose_name="болезненные половые акты"),
                ),
                (
                    "complaints_4",
                    models.BooleanField(
                        verbose_name="очень обильные кровотечения во время месячных"
                    ),
                ),
                (
                    "complaints_6",
                    models.BooleanField(verbose_name="показатель уровня гемоглобина "),
                ),
                (
                    "hemoglobin",
                    models.FloatField(blank=True, null=True, verbose_name="Гемоглобин"),
                ),
                (
                    "contraception",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Классификация миомы матки Международной федерации гинекологии и акушерства",
                    ),
                ),
                (
                    "myomatous_node_count",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("один(м.б.доминирующий)", "один(м.б.доминирующий)"),
                            ("2 - 3", "2 - 3"),
                            ("4 - 5", "4 - 5"),
                            ("более 5", "более 5"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Количество миоматозных узлов",
                    ),
                ),
                (
                    "diagnosis_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Объем миоматозных узлов, см3",
                    ),
                ),
                (
                    "with_adenomyosis",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Сочетание с аденомиозом"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseAnketa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("age_20_25", "20-25"),
                            ("age_26_30", "26-30"),
                            ("age_31_35", "31-35"),
                            ("age_36_40", "36-40"),
                            ("age_41_45", "41-45"),
                            ("age_46_50", "46-50"),
                        ],
                        max_length=15,
                    ),
                ),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorAnketa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contraception",
                    models.CharField(
                        max_length=100,
                        verbose_name="Классификация миомы матки Международной федерации гинекологии и акушерства",
                    ),
                ),
                (
                    "myomatous_node_count",
                    models.CharField(
                        choices=[
                            ("один(м.б.доминирующий)", "один(м.б.доминирующий)"),
                            ("2 - 3", "2 - 3"),
                            ("4 - 5", "4 - 5"),
                            ("более 5", "более 5"),
                        ],
                        max_length=50,
                        verbose_name="Количество миоматозных узлов",
                    ),
                ),
                (
                    "diagnosis_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Объем миоматозных узлов, см3",
                    ),
                ),
                (
                    "with_adenomyosis",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Сочетание с аденомиозом"
                    ),
                ),
                (
                    "resistance_index",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Индекс резистентности по данным ДМ",
                    ),
                ),
                ("mioma1", models.BooleanField(verbose_name="прогестагены")),
                (
                    "mioma2",
                    models.BooleanField(
                        verbose_name="комбинированные оральные контрацептивы"
                    ),
                ),
                (
                    "mioma3",
                    models.BooleanField(
                        verbose_name="агонисты гонадотропинрилизинг-гормона (аГн-РГ)"
                    ),
                ),
                ("mioma4", models.BooleanField(verbose_name="мифепристон")),
                ("mioma5", models.BooleanField(verbose_name="улипристала ацетат")),
                (
                    "surgical_treatment_in_history1",
                    models.BooleanField(
                        verbose_name="консервативная миомэктомия лапароскопическим доступом"
                    ),
                ),
                (
                    "surgical_treatment_in_history1_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "surgical_treatment_in_history2",
                    models.BooleanField(
                        verbose_name="консервативная миомэктомия лапаротомным доступом, год_____"
                    ),
                ),
                (
                    "surgical_treatment_in_history2_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "surgical_treatment_in_history3",
                    models.BooleanField(
                        verbose_name="гистероскопическое удаление подслизистых миоматозных узлов, год ______"
                    ),
                ),
                (
                    "surgical_treatment_in_history3_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "surgical_treatment_in_history4",
                    models.BooleanField(
                        verbose_name="окклюзия маточных артерий с помощью эмболизации, год_____"
                    ),
                ),
                (
                    "surgical_treatment_in_history4_year",
                    models.IntegerField(blank=True, null=True, verbose_name="Год"),
                ),
                (
                    "indication_for_treatment1",
                    models.BooleanField(verbose_name="АМК, приводящие к анемии"),
                ),
                (
                    "indication_for_treatment2",
                    models.BooleanField(
                        verbose_name="Хроническая тазовая боль, снижающая качество жизни"
                    ),
                ),
                (
                    "indication_for_treatment3",
                    models.BooleanField(
                        verbose_name="Симптомы сдавления смежных органов (прямая кишка, мочевой пузырь, мочеточники)"
                    ),
                ),
                (
                    "indication_for_treatment4",
                    models.BooleanField(
                        verbose_name="Большой размер опухоли (более 12 недель беременности)"
                    ),
                ),
                (
                    "indication_for_treatment5",
                    models.BooleanField(
                        verbose_name="Быстрый рост опухоли (увеличение матки более чем на 4 недели беременности в течение 1 года)"
                    ),
                ),
                (
                    "indication_for_treatment6",
                    models.BooleanField(verbose_name="Рост опухоли в постменопаузе"),
                ),
                (
                    "indication_for_treatment7",
                    models.BooleanField(
                        verbose_name="Подслизистое расположение узла миомы"
                    ),
                ),
                (
                    "indication_for_treatment8",
                    models.BooleanField(
                        verbose_name="Межсвязочное и низкое (шеечное и перешеечное) расположение узлов миомы"
                    ),
                ),
                (
                    "indication_for_treatment9",
                    models.BooleanField(
                        verbose_name="Нарушение репродуктивной функции (невынашивание беременности, бесплодие при отсутствии других причин"
                    ),
                ),
                (
                    "indication_for_treatment10",
                    models.BooleanField(
                        verbose_name="Признаки нарушения кровообращения в узлах миомы матки (некроз, отек, гиалиноз)."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodsAnketa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menarche",
                    models.CharField(
                        choices=[
                            ("24-38/3-8", "24-38/3-8"),
                            ("24-38/>8", "24-38/>8"),
                            ("23 и </3-8", "23 и </3-8"),
                            ("23 и </>8", "23 и </>8"),
                            ("другое", "другое"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periods_type",
                    models.CharField(
                        choices=[
                            ("Обильные", "Обильные"),
                            ("нормальные", "нормальные"),
                            ("судные", "судные"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_break", models.IntegerField()),
                (
                    "periods_break_variant",
                    models.CharField(
                        choices=[
                            ("24-38/3-8", "24-38/3-8"),
                            ("24-38/>8", "24-38/>8"),
                            ("23 и </3-8", "23 и </3-8"),
                            ("23 и </>8", "23 и </>8"),
                            ("другое", "другое"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "break_type",
                    models.CharField(
                        choices=[
                            ("Обильные", "Обильные"),
                            ("нормальные", "нормальные"),
                            ("судные", "судные"),
                        ],
                        max_length=20,
                    ),
                ),
                ("blood", models.BooleanField()),
                ("blood_year", models.IntegerField(blank=True, null=True)),
                ("pregnancy_parity", models.IntegerField(blank=True, null=True)),
                ("childbirth_count", models.IntegerField(blank=True, null=True)),
                ("abortion_count", models.IntegerField(blank=True, null=True)),
                (
                    "misbirth_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Выкидышей"
                    ),
                ),
                ("infertility_treatment", models.BooleanField(blank=True, null=True)),
                ("brt_program", models.BooleanField(blank=True, null=True)),
                (
                    "contraception",
                    models.CharField(
                        choices=[
                            ("прерванный половой акт", "прерванный половой акт"),
                            ("изделие №2", "изделие №2"),
                            ("спермициды", "спермициды"),
                            ("КГК", "КГК"),
                            ("чистые прогестины", "чистые прогестины"),
                            ("ВМК", "ВМК"),
                            ("рилизинг система Мирена", "рилизинг система Мирена"),
                            ("Нова-ринг", "Нова-ринг"),
                            ("Трансдермальная система", "Трансдермальная система"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "diseases_of_the_mammary_glands",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("доброкачественные", "доброкачественные"),
                            ("пограничные", "пограничные"),
                            ("злокачественные", "злокачественные"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Заболевания молочных желез",
                    ),
                ),
                (
                    "somatic_status",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Соматический статус"
                    ),
                ),
                (
                    "thyroid_gland_Pathology",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Патология щитовидной железы",
                    ),
                ),
                (
                    "anemia",
                    models.BooleanField(blank=True, null=True, verbose_name="Анемия"),
                ),
                (
                    "diagnosis_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год постановки диагноза"
                    ),
                ),
                (
                    "complaints_1",
                    models.BooleanField(
                        verbose_name="боль в пояснице, боли внизу живота, снижающие качество жизни"
                    ),
                ),
                (
                    "complaints_2",
                    models.BooleanField(
                        verbose_name="симптомы сдавления смежных органов (прямая кишка, мочевой пузырь, мочеточники)"
                    ),
                ),
                (
                    "complaints_3",
                    models.BooleanField(verbose_name="болезненные половые акты"),
                ),
                (
                    "complaints_4",
                    models.BooleanField(
                        verbose_name="очень обильные кровотечения во время месячных"
                    ),
                ),
                (
                    "complaints_5",
                    models.BooleanField(verbose_name="«мазня» в середине цикла"),
                ),
                (
                    "complaints_6",
                    models.BooleanField(verbose_name="снижение показателя гемоглобина"),
                ),
                (
                    "hemoglobin",
                    models.FloatField(blank=True, null=True, verbose_name="Гемоглобин"),
                ),
            ],
        ),
    ]
